import {
  Farm,
  Profile,
  Plot,
  CropCycle,
  Contact,
  InventoryItem,
  Worker,
  FarmTask,
  FinancialRecord,
  Investment,
} from '../types/database';

export const INITIAL_FARMS: Farm[] = [
  {
    id: 'farm-1',
    name: 'Plantation Agro-Ouest Bafoussam',
    location: 'Bafoussam, Région de l\'Ouest',
    plots: 4,
    size_in_hectares: 18.5,
    description: 'Exploitation mixte café, cacao et cultures maraîchères dans les Hauts-Plateaux.',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'farm-2',
    name: 'Ferme Vivrière Centre-Yaoundé',
    location: 'Nkolbisson, Yaoundé',
    plots: 3,
    size_in_hectares: 8.0,
    description: 'Production intensive de maïs, manioc et bananes plantains pour le marché de Yaoundé.',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'farm-3',
    name: 'Verger Littoral Douala-Dibombari',
    location: 'Dibombari, Région du Littoral',
    plots: 2,
    size_in_hectares: 12.0,
    description: 'Palmeraie et arbres fruitiers tropicaux (papaye, ananas, papayer).',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    email: 'admin@agriapp.cm',
    name: 'Jean-Paul Nkoumou',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    role: 'admin',
    farm_id: 'farm-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-manager-1',
    email: 'manager@agriapp.cm',
    name: 'Aline Fotso',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    role: 'manager',
    farm_id: 'farm-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-worker-1',
    email: 'worker@agriapp.cm',
    name: 'Samuel Mvondo',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    role: 'worker',
    farm_id: 'farm-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PLOTS: Plot[] = [
  {
    id: 'plot-1',
    farm_id: 'farm-1',
    name: 'Parcelle A - Cacao & Café Arabica',
    size_in_hectares: 6.5,
    soil_type: 'Volcanique',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plot-2',
    farm_id: 'farm-1',
    name: 'Parcelle B - Maraîchage & Tomate',
    size_in_hectares: 4.0,
    soil_type: 'Ferrallitique',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plot-3',
    farm_id: 'farm-1',
    name: 'Parcelle C - Plantain & Haricot',
    size_in_hectares: 5.0,
    soil_type: 'Argilo-limoneux',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plot-4',
    farm_id: 'farm-2',
    name: 'Parcelle Maïs Hybride - Nkolbisson',
    size_in_hectares: 5.0,
    soil_type: 'Sablonneux',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_CROP_CYCLES: CropCycle[] = [
  {
    id: 'crop-1',
    plot_id: 'plot-1',
    crop_name: 'Cacao',
    variety: 'Mercedes / Hybride IRAD',
    season: 'Saison des pluies 2024-2025',
    planting_date: '2024-04-15',
    expected_harvest_date: '2025-10-30',
    yield_in_kg: 3200,
    status: 'growing',
    estimated_cost_fcfa: 850000,
    revenue_fcfa: 4800000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crop-2',
    plot_id: 'plot-2',
    crop_name: 'Tomate',
    variety: 'Cobra F1',
    season: 'Campagne Maraîchère Bafoussam',
    planting_date: '2024-11-01',
    expected_harvest_date: '2025-02-28',
    actual_harvest_date: '2025-02-25',
    yield_in_kg: 8500,
    status: 'harvested',
    estimated_cost_fcfa: 600000,
    revenue_fcfa: 2550000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crop-3',
    plot_id: 'plot-3',
    crop_name: 'Plantain',
    variety: 'Batard / Big Ebanga',
    season: 'Saison 2024',
    planting_date: '2024-05-10',
    expected_harvest_date: '2025-06-15',
    status: 'planted',
    estimated_cost_fcfa: 450000,
    revenue_fcfa: 1800000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crop-4',
    plot_id: 'plot-4',
    crop_name: 'Maïs',
    variety: 'CMS 8704 (IRAD)',
    season: 'Saison S1 2025',
    planting_date: '2025-03-01',
    expected_harvest_date: '2025-07-20',
    status: 'planted',
    estimated_cost_fcfa: 350000,
    revenue_fcfa: 1200000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    name: 'Société Coopérative des Planteurs du Mungo (SOCOPMU)',
    type: 'customer',
    phone: '+237 6 99 12 34 56',
    email: 'achats@socopmu.cm',
    address: 'Kumba - Penja Highway, Région du Sud-Ouest',
    farm_id: 'farm-1',
    notes: 'Acheteur principal de fèves de cacao marchandes certifiées.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'contact-2',
    name: 'AgriTech Cameroun SARL (Engrais & Intrants)',
    type: 'supplier',
    phone: '+237 6 77 88 99 00',
    email: 'contact@agritech.cm',
    address: 'Bastos, Yaoundé',
    farm_id: 'farm-1',
    notes: 'Fournisseur d\'engrais NPK 20-10-10 et pulvérisateurs.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'contact-3',
    name: 'Marché Marchandises Mokolo Douala',
    type: 'customer',
    phone: '+237 6 55 44 33 22',
    address: 'Marché Marchandises Douala',
    farm_id: 'farm-2',
    notes: 'Grossiste en régimes de plantain et cagettes de tomates.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Engrais NPK 20-10-10 (Sacs 50kg)',
    category: 'input',
    quantity: 35,
    unit: 'sacs',
    price_per_unit: 28500, // FCFA
    farm_id: 'farm-1',
    supplier_id: 'contact-2',
    expiry_date: '2026-12-31',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    name: 'Fungicide Nordox 75 WG (Antifongique Cacao)',
    category: 'pesticide',
    quantity: 8,
    unit: 'boîtes 1kg',
    price_per_unit: 14500, // FCFA
    farm_id: 'farm-1',
    supplier_id: 'contact-2',
    expiry_date: '2025-08-15',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-3',
    name: 'Pulvérisateur à Dos Solo 15L',
    category: 'tool',
    quantity: 5,
    unit: 'unités',
    price_per_unit: 38000, // FCFA
    farm_id: 'farm-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-4',
    name: 'Semences Hybrides Tomate Cobra F1',
    category: 'input',
    quantity: 12,
    unit: 'sachets 100g',
    price_per_unit: 18000,
    farm_id: 'farm-1',
    supplier_id: 'contact-2',
    expiry_date: '2025-11-20',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-5',
    name: 'Cagettes en Plastique Rétractables',
    category: 'packaging',
    quantity: 120,
    unit: 'unités',
    price_per_unit: 2500,
    farm_id: 'farm-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'wrk-1',
    name: 'Samuel Mvondo',
    role: 'field_worker',
    phone_number: '+237 6 91 22 33 44',
    daily_wage: 3500, // FCFA per day
    farm_id: 'farm-1',
    is_active: true,
    total_tasks_completed: 42,
    productivity_score: 4.8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wrk-2',
    name: 'Emmanuel Talla',
    role: 'agronomist',
    phone_number: '+237 6 74 55 66 77',
    daily_wage: 8500, // FCFA
    farm_id: 'farm-1',
    is_active: true,
    total_tasks_completed: 31,
    productivity_score: 4.9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wrk-3',
    name: 'Christelle Nguema',
    role: 'supervisor',
    phone_number: '+237 6 95 11 22 33',
    daily_wage: 6000, // FCFA
    farm_id: 'farm-1',
    is_active: true,
    total_tasks_completed: 28,
    productivity_score: 4.6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'wrk-4',
    name: 'Bertrand Kemoe',
    role: 'machine_operator',
    phone_number: '+237 6 80 99 88 77',
    daily_wage: 5000, // FCFA
    farm_id: 'farm-2',
    is_active: true,
    total_tasks_completed: 19,
    productivity_score: 4.4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: FarmTask[] = [
  {
    id: 'task-1',
    worker_id: 'wrk-1',
    title: 'Émondage et désherbage parcelle Cacao A',
    description: 'Nettoyer les pieds de cacaoyers et éliminer les rejets parasitaires.',
    farm_id: 'farm-1',
    plot_id: 'plot-1',
    status: 'in_progress',
    assigned_date: '2025-02-20',
    due_date: '2025-02-28',
    wage_amount: 3500,
    wage_paid: true,
    notes: 'Priorité avant le début des premières pluies.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-2',
    worker_id: 'wrk-2',
    title: 'Traitement phytosanitaire fongicide Nordox',
    description: 'Traitement préventif contre la pourriture brune des cabosses de cacao.',
    farm_id: 'farm-1',
    plot_id: 'plot-1',
    status: 'pending',
    assigned_date: '2025-03-01',
    due_date: '2025-03-05',
    wage_amount: 8500,
    wage_paid: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-3',
    worker_id: 'wrk-1',
    title: 'Récolte et conditionnement des tomates Cobra F1',
    description: 'Tri selon le calibre A/B/C et mise en cagettes.',
    farm_id: 'farm-1',
    plot_id: 'plot-2',
    status: 'completed',
    assigned_date: '2025-02-22',
    due_date: '2025-02-25',
    completed_date: '2025-02-24',
    wage_amount: 3500,
    wage_paid: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-4',
    worker_id: 'wrk-4',
    title: 'Labourage mécanisé parcelle Maïs Nkolbisson',
    description: 'Passage du motoculteur et préparation des sillages de semis.',
    farm_id: 'farm-2',
    plot_id: 'plot-4',
    status: 'completed',
    assigned_date: '2025-02-15',
    due_date: '2025-02-18',
    completed_date: '2025-02-17',
    wage_amount: 5000,
    wage_paid: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_FINANCIALS: FinancialRecord[] = [
  {
    id: 'fin-1',
    type: 'income',
    amount: 2550000, // FCFA
    currency: 'XAF',
    date: '2025-02-25',
    description: 'Vente récolte Tomates Cobra (170 cagettes)',
    category: 'Vente Récolte',
    farm_id: 'farm-1',
    payment_method: 'orange_money',
    related_contact_id: 'contact-3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fin-2',
    type: 'expense',
    amount: 427500, // FCFA
    currency: 'XAF',
    date: '2025-02-10',
    description: 'Achat de 15 sacs engrais NPK 20-10-10',
    category: 'Achat Intrants',
    farm_id: 'farm-1',
    payment_method: 'mtn_momo',
    related_contact_id: 'contact-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fin-3',
    type: 'expense',
    amount: 105000, // FCFA
    currency: 'XAF',
    date: '2025-02-24',
    description: 'Paiement salaires hebdomadaires ouvriers agricoles',
    category: 'Salaires Ouvriers',
    farm_id: 'farm-1',
    worker_id: 'wrk-1',
    payment_method: 'cash',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fin-4',
    type: 'income',
    amount: 4800000, // FCFA
    currency: 'XAF',
    date: '2024-11-15',
    description: 'Vente 1.6 Tonnes de fèves de Cacao marchandes',
    category: 'Vente Récolte',
    farm_id: 'farm-1',
    payment_method: 'bank_transfer',
    related_contact_id: 'contact-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fin-5',
    type: 'expense',
    amount: 180000, // FCFA
    currency: 'XAF',
    date: '2025-01-18',
    description: 'Carburant Gasoil pour groupes électrogènes et motoculteurs',
    category: 'Carburant & Énergie',
    farm_id: 'farm-2',
    payment_method: 'orange_money',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_INVESTMENTS: Investment[] = [
  {
    id: 'invst-1',
    name: 'Système d\'Irrigation Goutte-à-Goutte Solaire',
    type: 'irrigation',
    amount: 3500000, // FCFA
    date: '2024-09-10',
    description: 'Installation de pompage solaire et tuyauterie pour la parcelle de tomate et maraîchage.',
    farm_id: 'farm-1',
    expected_return: 6000000, // FCFA
    return_date: '2026-09-10',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'invst-2',
    name: 'Séchoir Solaire Hybride pour Cacao & Café',
    type: 'infrastructure',
    amount: 2200000, // FCFA
    date: '2024-06-15',
    description: 'Shed de séchage protégé améliorant la qualité marchandise du cacao (grade 1).',
    farm_id: 'farm-1',
    expected_return: 4500000, // FCFA
    return_date: '2025-12-31',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'invst-3',
    name: 'Motoculteur Multifonction 12 CV Diesel',
    type: 'equipment',
    amount: 1800000, // FCFA
    date: '2024-03-20',
    description: 'Acquisition équipement de labour rapide et billonnage.',
    farm_id: 'farm-2',
    status: 'matured',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
